 # .travis.yml
language: node_js
node_js:
  - "6.9"
script:
  - bash ./scripts/deploy-to-gh-pages.sh
env:
  global:
    - GITHUB_REPO: "https://github.com/gdg-gandhinagar/Website"
    - secure: "oiwIJBiBZ1qN3sfJQPrRIdjb3RNNicHn76IqeEXxa5r5YcczqwPSl1KP9E2FtnDNcGKBHo43ActKXIdTAMULjJ9XpCa
UUrI8Nt1kQv5wbI7IzRigtsxtx9r0Dev9Lwze4X1tz7kpEEhuGcpFzpO3UXOHiYX9fqH9t47oLbt8YUN134zYRDTKXdZp+tdb7Dd4W
IcQAY5qX8Yjiu0QTWLzVa/fK8QlbDWzxcFVgg7YrjJtnkQHpJzGJafikpxkoavUBS0iDV7lBpRNGN7qAu1tVf7nHreVmlZnwK265ki
/5JXp1DBSHXMmP1++kg/g9IR/yfH5LbDpQUR6XR8uTIshtfHaJDzlFx2L58UJlAaprBunoasesrjqFsYH/XnbgNXpoCXLQsPNjx+3s
hIg10wxVkClxbUB7yowfUNsYv1Ch+eP53WUjsDnRiqG5X4NVxaAluiePYLCNtcpxyVCpWj8WfLY6nJ5Jl6wdosbXHVURu65ulA9U7y
pDoUzmoEmdtZomeDtamnuu5g2Oe8vAb6zJ2xRk9LzaORIHMgl2/vL4b0d7NQSsBSJwVIcb3b7YwXxz8CgzWODiRgscCrDMJlo8S38p
DsEqgBUx1eJuPhtcpriT5UPhvaonUjMRfUGDgsYjq9ARyAWhF7ruf2p8fmo8Wn8gSpqkHpSQiXBpGIoaDw="  # <-- from travis-encrypt